### PR TITLE
UART mode improvements

### PR DESCRIPTION
**Pull request by leethomason**
I love the AudioFX UART mode, and the help code is great to work through the details of the serial transmission. I did try to clean up a few issues:
- The file name/size cache is a significant amount of memory, and limits the class to working with 25 files. Both issues are addressed with a callback.
- Setting volume to a particular value is now supported. (Extra helpful in setup() if you are possibly overdriving your speaker.)
- Minor C++ cleanups.

### CODE REVIEW

**Comment by ladyada** [comment]
the problem with _not_ haveing a filename cache is that the arduino can't keep up and list all files otherwise...and its a huge debugging annoyance if it doesnt

**Comment by leethomason** [comment]
I understand your debugging concerns; but I think that the API will return a partial set is a bigger issue. And it's a fairly easy problem to hit, especially on a 16MB AudioFX board. I assure you the issue isn't theoretical. :)

Another approach would be for the user to provide the cache. So the user code would look something like:

```
FileInfo files[25];
audio.listFiles(files, 25, handler);
```

Where 'files' and 'handler' would both be optional. (And calling without both would just return the count.) So these are also valid:

```
int nFiles = audio.listFiles(0, 0, 0);
audio.listFiles(files, 25, 0);
```

That makes any limits obvious, and also makes the memory usage obvious.

**Comment by leethomason** [comment]
Updated the PR so it supports both methods. Does add some complexity to the listFiles() call, but hopefully the best of both worlds as far as debuggability and unlimited number of files.

**Comment by leethomason** [comment]
Closing since I (foolishly) opened a PR from master. Happy to re-open, or split the pull into smaller chunks if that's useful.

**Pull request closed without merging**
